# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|


   # install the chef client and chef solo
   #config.omnibus.chef_version = :latest
   
   # enable berkshelf
   #config.berkshelf.enabled = false


   config.vm.box = "precise64"
   config.vm.box_url = "http://files.vagrantup.com/precise64.box"

   #config.vm.provision :chef_solo do |chef|
   #    chef.roles_path   = "roles"
   #    chef.run_list     = ["role[fuseki-server]"]
   #end

   config.vm.provision :shell, :path => "bootstrap.sh"
   config.vm.network :forwarded_port, host: 4567, guest: 80

end
